#pragma once

#include <AP_HAL/AP_HAL_Boards.h>

#ifndef AP_SWARMMESH_ENABLED
#define AP_SWARMMESH_ENABLED HAL_PROGRAM_SIZE_LIMIT_KB > 2048
#endif

#ifndef AP_SWARMMESH_SITL_ENABLED
#define AP_SWARMMESH_SITL_ENABLED (AP_SWARMMESH_ENABLED && CONFIG_HAL_BOARD == HAL_BOARD_SITL)
#endif

#ifndef AP_SWARMMESH_MAX_PEERS
#define AP_SWARMMESH_MAX_PEERS 16
#endif