#pragma once

#include <AP_HAL/AP_HAL_Boards.h>

#ifndef AP_SWARMMESH_ENABLED
#define AP_SWARMMESH_ENABLED HAL_PROGRAM_SIZE_LIMIT_KB > 2048
#endif

#ifndef AP_SWARMMESH_TIMEOUT_MS
#define AP_SWARMMESH_TIMEOUT_MS 300
#endif

#ifndef AP_SWARMMESH_SERIAL_ENABLED
#define AP_SWARMMESH_SERIAL_ENABLED AP_SWARMMESH_ENABLED
#endif

#ifndef AP_SWARMMESH_SITL_ENABLED
#define AP_SWARMMESH_SITL_ENABLED (AP_SWARMMESH_ENABLED && CONFIG_HAL_BOARD == HAL_BOARD_SITL)
#endif

#ifndef AP_SWARMMESH_MAX_PEERS
#define AP_SWARMMESH_MAX_PEERS 16
#endif

// TX stream rates (Hz) for each hardware profile.
#ifndef AP_SWARMMESH_FULL_HZ
#define AP_SWARMMESH_FULL_HZ 200
#endif

#ifndef AP_SWARMMESH_LITE_HZ
#define AP_SWARMMESH_LITE_HZ 10
#endif